name: Publish

on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Upload Release Asset
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{  github.event.release.upload_url }}
          asset_path: ./dist/hwt.tar.gz
          asset_name: hwt.tar.gz
          asset_content_type: application/tar+gzip
